(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/xia-editor/xia-editor"],{"064f":function(t,e,n){"use strict";n.r(e);var i=n("e86c"),o=n("60c1");for(var c in o)"default"!==c&&function(t){n.d(e,t,(function(){return o[t]}))}(c);n("dfe5");var r,a=n("f0c5"),u=Object(a["a"])(o["default"],i["b"],i["c"],!1,null,null,null,!1,i["a"],r);e["default"]=u.exports},"60c1":function(t,e,n){"use strict";n.r(e);var i=n("dc5b"),o=n.n(i);for(var c in i)"default"!==c&&function(t){n.d(e,t,(function(){return i[t]}))}(c);e["default"]=o.a},"931c":function(t,e,n){},dc5b:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={props:{value:{type:String,default:""},placeholder:{type:String,default:"开始输入..."}},data:function(){return{readOnly:!1,formats:{}}},methods:{shibieText:function(t){var e=this;this.createSelectorQuery().select("#editor").context((function(n){e.editorCtx=n.context,e.editorCtx.setContents({html:t})})).exec()},editText:function(t){this.$emit("editorChange",t.detail.html)},readOnlyChange:function(){this.readOnly=!this.readOnly},onEditorReady:function(){var t=this;this.createSelectorQuery().select("#editor").context((function(e){t.editorCtx=e.context,setTimeout((function(){t.editorCtx.setContents({html:t.value})}),1e3)})).exec()},undo:function(){this.editorCtx.undo()},redo:function(){this.editorCtx.redo()},format:function(t){var e=t.target.dataset,n=e.name,i=e.value;n&&this.editorCtx.format(n,i)},onStatusChange:function(t){var e=t.detail;this.formats=e},insertDivider:function(){this.editorCtx.insertDivider({success:function(){console.log("insert divider success")}})},clear:function(){this.editorCtx.clear({success:function(t){console.log("clear success")}})},removeFormat:function(){this.editorCtx.removeFormat()},insertDate:function(){var t=new Date,e="".concat(t.getFullYear(),"/").concat(t.getMonth()+1,"/").concat(t.getDate());this.editorCtx.insertText({text:e})},insertImage:function(){var t=this;t.$api.upload((function(e){t.editorCtx.insertImage({src:t.$base.url+"upload/"+e.file,alt:"图像",success:function(){console.log("insert image success")}})}))}},onLoad:function(){t.loadFontFace({family:"Pacifico",source:'url("./Pacifico.ttf")'})}};e.default=n}).call(this,n("543d")["default"])},dfe5:function(t,e,n){"use strict";var i=n("931c"),o=n.n(i);o.a},e86c:function(t,e,n){"use strict";var i,o=function(){var t=this,e=t.$createElement;t._self._c},c=[];n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return c})),n.d(e,"a",(function(){return i}))}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/xia-editor/xia-editor-create-component',
    {
        'components/xia-editor/xia-editor-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("064f"))
        })
    },
    [['components/xia-editor/xia-editor-create-component']]
]);
